# Generated by Django 4.0 on 2021-12-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=128, unique=True),
        ),
    ]
