# Generated by Django 4.0 on 2022-01-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=128, verbose_name='Nom du club')),
                ('city', models.CharField(max_length=128, verbose_name='Ville')),
                ('province', models.CharField(max_length=128, verbose_name='Département')),
                ('genre', models.CharField(choices=[('women', 'féminine'), ('men', 'masculine')], default='', max_length=8)),
                ('level', models.CharField(max_length=128, verbose_name='Niveau')),
                ('season', models.PositiveSmallIntegerField(choices=[('Y-1', '2021-2022'), ('Y', '2022-2023'), ('Y+1', '2023-2024')], default='Y')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
