# Generated by Django 4.0 on 2022-01-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=128, verbose_name='Nom du club')),
                ('city', models.CharField(max_length=128, verbose_name='Ville')),
                ('province', models.CharField(max_length=128, verbose_name='Département')),
                ('genre', models.CharField(choices=[('féminine', 'féminine'), ('masculine', 'masculine')], default='WOMEN', max_length=9)),
                ('level', models.CharField(max_length=128, verbose_name='Niveau')),
                ('season', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default='Y', max_length=9)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
