# Generated by Django 4.0 on 2021-12-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='club_name',
        ),
    ]
