# Generated by Django 4.0 on 2022-01-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='genre',
            field=models.CharField(choices=[('féminine', 'féminine'), ('masculine', 'masculine')], default='féminine', max_length=9),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], default=('2022-2023', '2022-2023'), max_length=9),
        ),
    ]
