# Generated by Django 4.0 on 2022-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('Y-1', '2021-2022'), ('Y', '2022-2023'), ('Y+1', '2023-2024')], default='Y', max_length=9),
        ),
    ]
