# Generated by Django 4.0 on 2022-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='genre',
            field=models.CharField(choices=[('WOMEN', 'féminine'), ('MEN', 'masculine')], default='WOMEN', max_length=8),
        ),
    ]
