# Generated by Django 4.0.1 on 2022-01-10 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_team_genre_alter_team_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
    ]
