# Generated by Django 4.0.1 on 2022-01-10 16:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_team_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='Photo'),
        ),
    ]
