# Generated by Django 4.0 on 2021-12-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_rename_name_team_club_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom de famille')),
                ('jersey_number', models.CharField(max_length=2, verbose_name='Numéro de maillot')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Photo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.team')),
            ],
        ),
    ]
