# Generated by Django 4.0 on 2022-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom de famille')),
                ('jersey_number', models.CharField(max_length=2, verbose_name='Numéro de maillot')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
            ],
        ),
    ]
