# Generated by Django 4.0 on 2022-01-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_team_genre_alter_team_season'),
        ('player', '0002_alter_player_jersey_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number'), ('team', 'first_name', 'last_name')},
        ),
    ]
