# Generated by Django 4.0 on 2021-12-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Minutes jouées')),
                ('field_goals_made', models.PositiveSmallIntegerField(default=0, verbose_name='Tirs réussis')),
                ('field_goals_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='Tirs tentés')),
                ('three_points_made', models.PositiveSmallIntegerField(default=0, verbose_name='3pts réussis')),
                ('three_points_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='3pts ratés')),
                ('free_throws_made', models.PositiveSmallIntegerField(default=0, verbose_name='LF tentés')),
                ('free_throws_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='LF tentés')),
                ('offensive_rebounds', models.PositiveSmallIntegerField(default=0, verbose_name='Rebonds offensifs')),
                ('defensive_rebounds', models.PositiveSmallIntegerField(default=0, verbose_name='Rebonds défensifs')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Passes décisives')),
                ('steals', models.PositiveSmallIntegerField(default=0, verbose_name='Interceptions')),
                ('blocks', models.PositiveSmallIntegerField(default=0, verbose_name='Contres')),
                ('turnovers', models.PositiveSmallIntegerField(default=0, verbose_name='Ballons perdus')),
                ('fouls', models.PositiveSmallIntegerField(default=0, verbose_name='Fautes')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='player.player')),
            ],
        ),
    ]
