# Generated by Django 4.0 on 2021-12-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_made', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_attempted', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_percentage', models.PositiveSmallIntegerField(default=0)),
                ('three_points_made', models.PositiveSmallIntegerField(default=0)),
                ('three_points_attempted', models.PositiveSmallIntegerField(default=0)),
                ('three_points_percentage', models.PositiveSmallIntegerField(default=0)),
                ('free_throws_made', models.PositiveSmallIntegerField(default=0)),
                ('free_throws_attempted', models.PositiveSmallIntegerField(default=0)),
                ('free_throws_percentage', models.PositiveSmallIntegerField(default=0)),
                ('rebounds', models.PositiveSmallIntegerField(default=0)),
                ('offensive_rebounds', models.PositiveSmallIntegerField(default=0)),
                ('defensive_rebounds', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('steals', models.PositiveSmallIntegerField(default=0)),
                ('blocks', models.PositiveSmallIntegerField(default=0)),
                ('turnovers', models.PositiveSmallIntegerField(default=0)),
                ('fouls', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticPlayer',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statistic')),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('statistic.statistic',),
        ),
        migrations.CreateModel(
            name='StatisticTeam',
            fields=[
                ('statistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistic.statistic')),
            ],
            bases=('statistic.statistic',),
        ),
    ]
