# Generated by Django 4.0 on 2022-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='did_he_play',
            field=models.BooleanField(default=False),
        ),
    ]
