# Generated by Django 4.0 on 2021-12-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('opponent', models.CharField(max_length=128)),
                ('opponent_points', models.PositiveSmallIntegerField(default=0, verbose_name="Points de l'adversaire")),
                ('comment', models.TextField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='team.team')),
            ],
        ),
    ]
