# Generated by Django 4.0 on 2022-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.TextField(null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.CharField(max_length=128, verbose_name='Adversaire'),
        ),
        migrations.AlterField(
            model_name='game',
            name='place',
            field=models.CharField(choices=[('à domicile', 'à domicile'), ("à l'extérieur", "à l'extérieur"), ('sur terrain neutre', 'sur terrain neutre')], default='à domicile', max_length=18, verbose_name='Lieu'),
        ),
    ]
