# Generated by Django 4.0 on 2022-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='place',
            field=models.CharField(choices=[('home', 'à domicile'), ('away', "à l'extérieur"), ('neutral', 'sur terrain neutre')], default='neutral', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='team_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Points de l'équipe"),
        ),
    ]
